### ISSUE TITLE
nuxt-bridge vite: true

### ISSUE THREAD

**Issue by yinfoyuan** [posva/pinia#768] opened 2021-11-04 09:59 UTC
```
  bridge: {
    vite: true
  },
```

https://codesandbox.io/s/shy-darkness-ly17m?file=/nuxt.config.ts

**Comment by posva** [comment] 2021-11-04 15:38
This is not even a valid issue... But I guess this is a duplicate of https://github.com/posva/pinia/issues/690

**Closed as completed by posva** 2021-11-04 15:38 UTC
