### ISSUE TITLE
Add support for automatic imports of stores for nuxt applications

### ISSUE THREAD

**Issue by Rednas83** [posva/pinia#1998] opened 2023-02-11 21:24 UTC
### What problem is this solving

Not required to manually import stores at different levels (page, component, composable, plugin, etc) inside a nuxt application.

### Proposed solution

```
// nuxt.config.js
export default defineNuxtConfig({
  modules: ['@pinia/nuxt'],
  pinia: {
    autoImports: ['defineStore', 'skipHydrate', 'useCounterStore'],
  }
})
```

### Describe alternatives you've considered

Manually import the stores for every page/component/composable/etc

`import useCounterStore from "../stores/useCounterStore"`

**Comment by posva** [comment] 2023-02-11 21:55
Duplicate of https://github.com/vuejs/pinia/pull/1604

**Closed as not planned** 2023-02-11 21:55 UTC
Labels: feature request

**Comment by Rednas83** [comment] 2023-02-12 09:20
Yeah, autoImporting the **../stores** folder or a custom folder would be even better as suggested in #1604
