### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'effect')

### ISSUE THREAD

**Issue by maxfrees** [posva/pinia#2852] opened 2024-12-07 13:53 UTC
### Reproduction

-

### Steps to reproduce the bug

TypeError: Cannot read properties of undefined (reading 'effect')

in 2.2.7 its ok, but 2.30 not work

```
const { debugConfig } = storeToRefs(appStore);
console.log(debugConfig)


export const useAppStore = defineStore(
  'app',
  () => {
    const debugConfig = ref<DebugType>({
      support: false,
      enabled: false,
      owner: false
    });
    return {debugConfig}
    }
```

![image](https://github.com/user-attachments/assets/5b52a9f4-48de-4cdc-892a-8505e4df19a6)

### Expected behavior

TypeError: Cannot read properties of undefined (reading 'effect')

### Actual behavior

TypeError: Cannot read properties of undefined (reading 'effect')

**Comment by mnmnk43434** [comment] 2024-12-07 13:57
Hello, we tried to solve the issue.

This is what we did:

Update the isComputed function to check if the value is defined and has an 'effect' property before accessing it. This should resolve the TypeError when dealing with undefined values.

You can review changes in this commit: https://github.com/mnmnk43434/vuejs-pinia-2852/commit/8d62e54136965638b9258967e8cac6663fa7dbf5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by posva** [comment] 2024-12-07 15:33
[The code you provided works](https://play.pinia.vuejs.org/#eNqNVMFu2zAM/RXBlzhAI63I0AFZHGQretgO29D26Itj064yWRIkOTFg+N9HybHrZkOxm0Q+Pj4+me6iL1rTUwPRJtra3HDtiAXXaCIyWSVp5Gwa7VLJa62MIx1pLDw5ZYD0pDSqJgvKctVIB4Y6u5gBrUc9q0co7YTVXPIMQanMlbTYKTAlE2m8HDMdKeDQVPdKlrzC+mTOF4fz8vMAVgKoUFU8K0CaLRumQe14cVBrkTnAGyFbbWDXXXXot8yHfeEMHN1Ew0CrOtP0aJVEnzpPkl4SaM+GhIiPhQF9JI1YOFOw9epg1NmiQUcE34zQPZrOCjg5pYRdZZoPZS/OabthLC8k4gsQ/GSoBMekrtlfNfs7ekdvmeAHho0YlwW0b9tgxaqA+n/YR+j+A739SD8F1tP6Qlp7Vk/ap7JHW5xF79G5K1NyVWsuwPzUjuPbvDEnE0Kdv4eYMw1MEvMXyH//I3607aD6lwG07wSzsVxmKnBD+uHpB7R4npK1KhqB6HeSj4DfTeM1DrCvjSxQ9gwX1H4Lb8xl9WwfWgfSjkN5ocGNgA82378z+qvcNV3PXHxdHbRwWp0CSi6v1mxcnQlkoJyS2D1sVSqhDelhiaZdTeaUse+/yLReBO3xkiS7UelQN1+MxDeKL2lCbKN9gw0pM2HHpyIEZHYQUFyH1VmCuQSHWO+31h8M/mSMJN2sF3oyQKL+DxfBiwI=). Please take the time to actually provide a repro when opening an issue.

**Comment by posva** [comment] 2024-12-07 15:33
Duplicate of #2848

**Closed as not planned by posva** 2024-12-07 15:33 UTC
