### ISSUE TITLE
Type of WritableComputedRef from store is read-only

### ISSUE THREAD

**Issue by Jaykob86** [posva/pinia#2774] opened 2024-09-17 19:42 UTC
### Reproduction

https://play.pinia.vuejs.org/#eNqNVMFu2zAM/RXBl6RoIrXo0AFBUmQbeugO29Du6ItjM6lSiRIk2Q0Q+N9HS47rZkOxm0U+Pj4+iT5mX6zlTQ3ZIlv60kkbmIdQW6YK3K3yLPg8u8tRamtcYEdWe3gKxgFr2dYZzSZclKbGAI4HP8kxx9KgJ5IIWg346UWOS5E6EB8dAmirigB0Ymy5qUMwyNalkuUL9Y31HC8vqf0Dlg40IPU/JmKOrG2XIhURwVKM2LJZluTOdWH53huk4Y5dl7xP0EwLFiNdzEqURRfJMxG/OXg93zjz6mmqPYFnJ+ianBIVNMEY5eeFlansOQTrF0KUFRK+AiUbxxGCQKvFXzXrW37Lr4WSG0GNhMQKDu/bUMW8Av0/7Cfo+opff+KfI2tz05PqjrUjbXNsyZbg6XK2cndmSmm0lQrcTxskXd47cwqlzOv3GAuuhkFi+Qzlyz/ie39Iqn85IPsaGI0VCreDkNL3Tz/gQN9DUpuqVoT+IPkI3qi605hgX2usSPYIF9U+xDuWuPvt7w8B0J+G6oRGNyI+2vztg9Hf5N7wm5GLb++dLBwWo4KtxLPdiK+JlmIAOdjOWGd3HaAaYKQjbg4cIiwt0LBoqzH1dNJ3n8zY9IKt7pLcVIKPsCU4NZle0bqNEhQ9dZ3GAhps0RN0VbwpVH+JtP2Uac5SRNBEC3peR/8IhzQRLSK5QtGs/QNS/nB3

### Steps to reproduce the bug

WritableComputedRef from store shows as read-only by typescript. Both getter and setter works, but Typescript error needs to be supressed.

```
import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useStore = defineStore('counter', () => {
  const nRef = ref(0)

  const n = computed({
  get: () => nRef.value,
  set: (v) => nRef.value = v
  })

  return { n }
})
```

`store.n++` shows TS error `Cannot assign to 'n' because it is a read-only property.`
```
<script setup lang="ts">
import { useStore } from './counter.ts'

const store = useStore()
</script>

<template>
  <button @click="store.n++">Increment {{ store.n }}</button>
</template>
```

### Expected behavior

There should be no Typescript error as WritableComputedRef should be writable.

### Actual behavior

WritableComputedRef from store shows as read-only in components by typescript. Both getter and setter works, but Typescript error needs to be supressed.

**Comment by posva** [comment] 2024-09-18 06:25
Duplicate of #2767

**Closed as not planned by posva** 2024-09-18 06:25 UTC
