### ISSUE TITLE
Private fields in a class triggers TypeScript Error: incompatible type

### ISSUE THREAD

**Issue by dulimarta** [posva/pinia#1427] opened 2022-07-06 17:03 UTC
### Reproduction

https://codesandbox.io/s/happy-volhard-03rj6n?file=/src/index.ts

### Steps to reproduce the bug

Use the code example on CodeSandbox.io

1. Edit `Counter.ts` , remove the `private` keyword. The compiler error message at line 8 of `index.ts` will disappear

### Expected behavior

No compile error at line 8 of `index.ts`

### Actual behavior

When a class field is declared with `private` or `protected`, any references to the object object of the class is missing the private field.

### Additional information

My current workaround is to typecast the object in the array by replacing

```
s.arr.forEach((a: Counter) => { /* code */ ]);
```
with
```
s.arr.map(x => x as Counter)
 .forEach((a: Counter) => { /* code */ ]);
```

**Comment by posva** [comment] 2022-07-07 11:40
Duplicate of https://github.com/vuejs/core/issues/2981

**Comment by posva** [comment] 2022-07-07 11:41
Note that using classes in state won't work during SSR serialization, you need to use serializable state.

**Closed as not planned by posva** 2022-07-07 11:40 UTC
