### ISSUE TITLE
Documentation page (pinia.vuejs.org) dark mode toggle going haywire

### ISSUE THREAD

**Issue by kwshi** [posva/pinia#1028] opened 2022-02-04 07:05 UTC
This is not a bug with Pinia itself; just its documentation page.  The bug makes reading the documentation very painful.  Out of nowhere, the page decided to go haywire toggling to dark mode and back:

![pinia-docs-dark-mode-crazy](https://user-images.githubusercontent.com/3887189/152486458-7a712f16-9e4e-418d-ac64-610d5a4de7ad.gif)

FYI, I am on Firefox 96.0.2, Void Linux.

**Comment by posva** [comment] 2022-02-04 08:32
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Comment by posva** [comment] 2022-02-04 08:33
Duplicate of #829

**Closed as completed by posva** 2022-02-04 08:32 UTC
