### ISSUE TITLE
Persisted state after page reload! 

### ISSUE THREAD

**Issue by folamy** [posva/pinia#876] opened 2021-12-05 09:13 UTC
What is the standard way to persist a state in Pinia?  
I'm using nuxt3, and I get  hydration warnings when I do this: 

```js
// app.vue
cartStore.$subscribe((mutation, state) => {
  // persist the whole state to the local storage whenever it changes
  localStorage.setItem('cart', JSON.stringify(state))
})


onbeforeMount(() => {
 cartStore.$state = JSON.parse(localStorage.getItem('cart'))
})
```
This seems to work with a bunch of hydration errors/warnings in the console after a full page reload. 
Is there a better way to persist a state?

**Comment by posva** [comment] 2021-12-05 17:17
Duplicate of https://github.com/posva/pinia/issues/309

**Comment by posva** [comment] 2021-12-05 17:17
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as completed by posva** 2021-12-05 17:17 UTC
