### ISSUE TITLE
Using TypeScript Classes in stores gets downgraded to objects with only the public keys

### ISSUE THREAD

**Issue by araney** [posva/pinia#1984] opened 2023-02-07 03:01 UTC
### Reproduction

https://github.com/araney/vitejs-vite-z7xdkr

### Steps to reproduce the bug

Open the repo in Visual Studio Code with the Volar extension
Open the App.vue file
Notice the error when binding `models` to `:models` on the `Child` component.

### Expected behavior

No error should come up, as the type of the `models` ref *should* be `Ref<Model[]>`, and the type of the prop is `Model[]`.

### Actual behavior

An error comes up because the `models` ref is not of type `Ref<Model[]>`, but instead `Ref<{id: string, name: string}[]>`. 
The class type being used is getting boiled down to an object with matching public properties. But the private properties are missing, which causes a TypeScript type error. The type information of the class type being used should be persisted.

### Additional information

Type of the data on the pinia store:
![image](https://user-images.githubusercontent.com/5825171/217136895-544be4a1-98f5-4067-b5fd-853efe5f21bb.png)

Type of the `storeToRef` imported ref:
![image](https://user-images.githubusercontent.com/5825171/217136969-f5f10b68-2730-4349-b4db-73fe21a6233b.png)

Error provided by the binding:
![image](https://user-images.githubusercontent.com/5825171/217137074-812b2ac2-53ee-4f18-af17-efdf3d2e4f8a.png)

Note that this error also occurs if we use a computed to access `store.models` instead of `storeToRef`, and even occurs if we bind directly to the store with `:models="store.models"`.

Compilation does not fail, and the code runs properly in the browser.

**Comment by posva** [comment] 2023-02-07 07:58
Duplicate of https://github.com/vuejs/pinia/issues/1427

**Comment by posva** [comment] 2023-02-07 07:59
This might help https://github.com/vuejs/pinia/issues/1401#issuecomment-1309087503

---

Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as not planned by posva** 2023-02-07 07:58 UTC
