### ISSUE TITLE
getters are undefined after hydration in nuxt app

### ISSUE THREAD

**Issue by vuejstime** [posva/pinia#670] opened 2021-09-11 16:24 UTC
hello
### Steps to reproduce the behavior
1. create a directory called ```store-pinia```
2. create a file called ```counter.store.ts```
3. put this basic code in
```
import { defineStore } from 'pinia';
export const useStore = defineStore('main', {
  state: () => ({
    counter: 1,
  }),
  getters: {
    // automatically infers the return type as a number
    doubleCount(state) {
      return state.counter * 2
    },
    // the return type **must** be explicitly set
    doublePlusOne(): number {
      // autocompletion and typings for the whole store ✨
      return this.counter * 2 + 1
    },
  },
})

````
4. put this code in a vue component
```
<template>
<div>
  <p>Double count is {{ store.counter }}</p>
  <p>Double count is {{ store.doubleCount }}</p>
  <p>Double count is {{ store.doublePlusOne }}</p>
</div>
</template>

<script>
import { watchEffect } from 'vue-demi'
import { useStore } from '~/store-pinia/counter.store'

export default {
  setup() {
    const store = useStore()
    watchEffect(() => {
      console.log('store', store)
    })
    return { store }
  },
}
</script>


```

### Expected behavior

get 1 next line 2 next line 3

### Actual behavior

getters turned to undefined after a quick flash (hydration)

### Additional information

i'm using vuex beside pinia
and also nuxt-typed-vuex for ts support in vuex

my versions are:
```
"@pinia/nuxt": "^0.0.2",
 "pinia": "^2.0.0-rc.8",
  "nuxt": "^2.15.8",
  "@nuxtjs/composition-api": "^0.29.0",
```

**Comment by vuejstime** [comment] 2021-09-11 16:43
i also have this warning in the server
```[Vue warn]: toRefs() expects a reactive object but received a plain one.```

**Comment by posva** [comment] 2021-09-11 17:32
Duplicate of #660

**Closed as completed by posva** 2021-09-11 17:32 UTC

**Comment by vuejstime** [comment] 2021-09-11 18:27
just one question ```https://github.com/posva/pinia-example-nuxt/```
this example is working but when delete yarn.lock and reinstall packages it's not working.
please tell me how can i set proper versions to work? actually i'm in a bad trubble

**Comment by ziaadini** [comment] 2021-09-11 18:39
> just one question `https://github.com/posva/pinia-example-nuxt/`
> this example is working but when delete yarn.lock and reinstall packages it's not working.
> please tell me how can i set proper versions to work? actually i'm in a bad trubble

Same question
