### ISSUE TITLE
defineStore seems to loose types informations 

### ISSUE THREAD

**Issue by alshyra** [posva/pinia#2139] opened 2023-04-13 09:33 UTC
### Reproduction

https://github.com/alshyra/pinia-reproduce-type-issue

### Steps to reproduce the bug

1. Create a store (option or composition)
2. Create an state typed by a class (it get's funny with a private member) for this example let's a simple one:
```
class MyClass {
  attr: string;
}
```
3. use the store with `storeToRefs` for example in any component and inspect the type

### Expected behavior

```
Ref<MyClass>
``` 

### Actual behavior

```
Ref<{attr: string}>
```

### Additional information

I checked the issue backlog but I'm not sure if there is any related to this.

**Comment by posva** [comment] 2023-04-13 09:58
Duplicate of https://github.com/vuejs/pinia/issues/1984

**Comment by posva** [comment] 2023-04-13 09:58
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as not planned by posva** 2023-04-13 09:58 UTC
