### ISSUE TITLE
Persistent Support

### ISSUE THREAD

**Issue by nicojmb** [posva/pinia#357] opened 2021-02-08 18:23 UTC
Hi,

i'm newest on Vue and Pinia bit this Code is great.

My question is,  Exists support for permanent storage or and example how implement with pinia and vue3?

**Comment by posva** [comment] 2021-02-08 18:25
Duplicate of https://github.com/posva/pinia/issues/309

**Closed as completed by posva** 2021-02-08 18:25 UTC

**Comment by Fanna1119** [comment] 2021-04-01 11:32
Closed but a worthy mention. I am not sure how problematic it would be for bigger apps but so far i haven't run in any problems using a reactive storage composable:
https://vueuse.org/core/usestorage/

It also has type declarations.
https://vueuse.org/core/usestorage/#type-declarations

i have used this in vuex as well without any issues.
this of course does not solve #191 and #309

//store
```js


import { defineStore } from 'pinia'
import { useStorage } from '@vueuse/core'

export const useMainStore = defineStore({
    id: 'main',
    state: () => ({
        counter: useStorage('my-count', 0),
    }),
    getters: {
        doubleCount() {
            return this.counter * 2
        },
    },
    actions: {
        reset() {
            this.counter = 0
        },
        inc() {
            this.counter++;
        }
    },
})


```

```vue

<template>
  <div>
    {{ doubleCount }}
    {{counter}}
    <button @click="inc">inc</button>
    <button @click="reset">reset</button>
  </div>
</template>

<script>
import { useMainStore } from "@store/mainStore.js";
import { computed } from "@vue/runtime-core";
export default {
  setup() {
    const main = useMainStore();

    main.$patch({
      counter: main.counter + 1,
    });

    return {
      doubleCount: computed(() => main.doubleCount),
      inc: main.inc,
      reset: main.reset,
      counter: computed(() => main.counter)
    };
  },
};
</script>

```

**Comment by dystopiandev** [comment] 2021-05-31 02:52
> Closed but a worthy mention. I am not sure how problematic it would be for bigger apps but so far i haven't run in any problems using a reactive storage composable:
> https://vueuse.org/core/usestorage/
> 
> It also has type declarations.
> https://vueuse.org/core/usestorage/#type-declarations
> 
> i have used this in vuex as well without any issues.
> this of course does not solve #191 and #309
> 
> //store
> 
> ```js
> import { defineStore } from 'pinia'
> import { useStorage } from '@vueuse/core'
> 
> export const useMainStore = defineStore({
>     id: 'main',
>     state: () => ({
>         counter: useStorage('my-count', 0),
>     }),
>     getters: {
>         doubleCount() {
>             return this.counter * 2
>         },
>     },
>     actions: {
>         reset() {
>             this.counter = 0
>         },
>         inc() {
>             this.counter++;
>         }
>     },
> })
> ```
> 
> ```
> <template>
>   <div>
>     {{ doubleCount }}
>     {{counter}}
>     <button @click="inc">inc</button>
>     <button @click="reset">reset</button>
>   </div>
> </template>
> 
> <script>
> import { useMainStore } from "@store/mainStore.js";
> import { computed } from "@vue/runtime-core";
> export default {
>   setup() {
>     const main = useMainStore();
> 
>     main.$patch({
>       counter: main.counter + 1,
>     });
> 
>     return {
>       doubleCount: computed(() => main.doubleCount),
>       inc: main.inc,
>       reset: main.reset,
>       counter: computed(() => main.counter)
>     };
>   },
> };
> </script>
> ```

Here's a handy serialization composable, if anyone else opts in for this approach:
```ts
export const useStoreStateSerializer = () => ({
  write(val: unknown) {
    return JSON.stringify(val)
  },
  read(raw: string) {
    return JSON.parse(raw)
  }
})
```

**Comment by Ryan-Vablet** [comment] 2021-07-25 06:59
@dystopiandev thanks for saving my weekend trying to deal with this! It works flawlessly for me on latest vue3 and pinia. 

Also just a cool library I was unaware of thanks much!
