### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'pinia\dist\pinia'

### ISSUE THREAD

**Issue by GhostWolf01** [posva/pinia#1542] opened 2022-08-11 15:35 UTC
### Reproduction

use @pinia/nuxt: v4.0.0, pinia: 2.0.18, nuxt: 3.0.0-rc.6, 

### Steps to reproduce the bug

npm run build
node .output/server/index.mjs
open page
[nuxt] [request error] Cannot find module 'pinia\dist\pinia' imported from .output\server\chunks\server.mjs
  at new NodeError (internal/errors.js:322:7)
  at finalizeResolution (internal/modules/esm/resolve.js:318:11)
  at moduleResolve (internal/modules/esm/resolve.js:776:10)
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
  at Loader.resolve (internal/modules/esm/loader.js:89:40)
  at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
  at link (internal/modules/esm/module_job.js:75:36)
  
  fix: from 'pinia\dist\pinia.mjs'

### Expected behavior

No error Cannot find module 'pinia\dist\pinia'

### Actual behavior

Error Cannot find module 'pinia\dist\pinia'

### Additional information

 use @pinia/nuxt: v3.1.0 no error

**Comment by danielroe** [comment] 2022-08-11 18:24
Would you provide a reproduction? 🙏

**Comment by GhostWolf01** [comment] 2022-08-11 19:10
Reproduction: https://stackblitz.com/edit/nuxt-starter-hvks65?file=package.json,store%2FuseAppStore.js,app.vue

**Comment by ghost** [comment] 2022-08-11 21:20
I had some issues with `pinia/nuxt: v0.4.0` and `nuxt: 3.0.0-rc.6` too, the dev server was starting but got a 404 on client.ts. 

After updating nuxt to `3.0.0-rc.7`, everything was working again. So maybe this resolves your issue too.

**Comment by shtse8** [comment] 2022-08-12 00:26
> I had some issues with `pinia/nuxt: v0.4.0` and `nuxt: 3.0.0-rc.6` too, the dev server was starting but got a 404 on client.ts.
> 
> After updating nuxt to `3.0.0-rc.7`, everything was working again. So maybe this resolves your issue too.

I had the same issue too. 

after upgrading nuxt to `3.0.0-rc.7`
another error occur:
```
yarn run v1.22.19
$ nuxi build
Nuxt CLI v3.0.0-rc.7                                                                                                                                                                                                                                                        08:27:43

 ERROR  nuxtCtx.tryUse is not a function                                                                                                                                                                                                                                    08:27:47  

  at useNuxt (/D:/project/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:47:28)
  at extendViteConfig (/D:/project/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:772:16)
  at addVitePlugin (/D:/project/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:798:3)
  at initNuxt (/D:/project/node_modules/nuxt/dist/index.mjs:1441:3)
  at Object.ready (/D:/project/node_modules/nuxt/dist/index.mjs:1419:18)
  at loadNuxt (/D:/project/node_modules/nuxt/dist/index.mjs:1522:16)
  at async loadNuxt (/D:/project/node_modules/@nuxt/kit/dist/index.mjs:687:19)
  at async Object.invoke (/D:/project/node_modules/nuxi/dist/chunks/build.mjs:29:18)
  at async _main (/D:/project/node_modules/nuxi/dist/cli.mjs:46:20)

```

**Comment by ghost** [comment] 2022-08-12 10:04
I guess your issue is now more related to the changes in `3.0.0-rc.7` and not pinia. 

Maye a look into the changelog could help: https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.7

Maybe the changes from https://github.com/nuxt/framework/pull/6025 are related to your issue, but only a wild guess without seeing any code, but this would then be discussed in the Nuxt repo anyways.

**Comment by danielroe** [comment] 2022-08-12 11:38
Yes, see https://github.com/nuxt/nuxt.js/issues/14538. (Should be resolved by updating `unctx` dependency with upgrade/update command.)

I'm going to close this issue as I don't think there is now a remaining issue related to pinia, but please feel free to reply if not and I can reopen.

**Closed as completed** 2022-08-12 11:38 UTC

**Comment by markgibbons25** [comment] 2022-09-07 01:56
I got this issue on `nuxt 3.0.0-rc.9` and resolved it by running `npm i pinia -f`. Digging into why , it looks like npm 8.x wasn't installing pinia due to a vue compatibility issue.

**Comment by LastxTemplar** [comment] 2022-09-12 15:28
> I got this issue on `nuxt 3.0.0-rc.9` and resolved it by running `npm i pinia -f`. Digging into why , it looks like npm 8.x wasn't installing pinia due to a vue compatibility issue.

This is the only solution that helped! thank you!

**Comment by IsmaelBPS** [comment] 2022-10-04 17:16
> I got this issue on `nuxt 3.0.0-rc.9` and resolved it by running `npm i pinia -f`. Digging into why , it looks like npm 8.x wasn't installing pinia due to a vue compatibility issue.

Worked for me too.

**Comment by doniecliff** [comment] 2023-11-15 01:50
I used this solution.. and it worked for me

{ err;
Cannot restart nuxt:  Cannot find module 'pinia/dist/pinia.mjs' }

in > nuxtConfig

```typescript
  alias: {
    pinia: "/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs"
  },

``` 


do u think they they might be an issue with this temp.. fix (until the issue is resolved with npm or pinia 
from: https://stackoverflow.com/a/74801367

**Comment by ghost** [comment] 2024-01-08 23:42
> ```ts
>   alias: {
>     pinia: "/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs"
>   },
> ```

Since **Pinia** is installed by **@pinia/nuxt**, no need forcing it to install again when the alias works fine until the issue is resolved.

**Comment by frank-topel-dbi** [comment] 2024-09-10 12:05
> do u think they they might be an issue with this temp.. fix (until the issue is resolved with npm or pinia from: https://stackoverflow.com/a/74801367

Applying your `alias` fix gives me

```
ERROR  Pre-transform error: Failed to resolve import "pinia" from "node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js?v=77ca2bdd". Does the file exist?
```

when running the Nuxt dev server.
