### ISSUE TITLE
`storeAsRefs` doesn't work - values resolve to `undefined`

### ISSUE THREAD

**Issue by wujekbogdan** [posva/pinia#1079] opened 2022-02-18 10:33 UTC
### Reproduction

``` vue
<template>
  <div>
    <p>works: {{ works }}</p>
    <p>doesNotWork: {{ doesNotWork }}</p>
    <p>doesNotWorkEither: {{ doesNotWorkEither }}</p>
  </div>
</template>

<script>
import { defineComponent, computed } from "@vue/composition-api";
import { storeToRefs } from "pinia";
import useDemoStore from "./store";

export default defineComponent({
  setup() {
    const demoStore = useDemoStore();
    const { demoValue } = storeToRefs(demoStore);
    const storeAsRefs = storeToRefs(demoStore);

    demoStore.init();

    return {
      works: computed(() => demoStore.demoValue),
      doesNotWork: demoValue,
      doesNotWorkEither: storeAsRefs.demoValue,
    };
  },
});
</script>
```

``` js
// store.js
import { defineStore } from "pinia";

const useMainStore = defineStore("demo", {
  state: () => ({
    demoValue: 0
  }),

  actions: {
    async init() {
      setInterval(() => {
        this.demoValue += 1;
      }, 1000);
    }
  }
});

export default useMainStore;
```

``` js 
// package.json
"dependencies": {
    "vue": "^2.6.6",
    "pinia": "^2.0.11",
    "@vue/composition-api": "^1.4.6",
}
```

---
I tried to reproduce the bug on CodeSandbox, but I got stuck at `(0 , $csb__vue_demi.effectScope) is not a function` error: https://codesandbox.io/s/laughing-glitter-7ixf5u?file=/src/StoreToRefsDemo.vue

### Steps to reproduce the behavior

1. Use Vue 2.x with Composition API plugin
2. Create a store
2. Set state, e.g. using an action
3. Import that store in a component
4. Use `storeToRefs` to extract state
5. Export extracted refs
6. Use them in the template

### Expected behavior

The template renders the values as expected

### Actual behavior

- Values extracted with `storeToRefs` resolve with `undefined`.
- Values accessed via `computed(() => demoStore.demoValue)` render as expected.

<img width="300" alt="Zrzut ekranu 2022-02-18 o 11 03 13" src="https://user-images.githubusercontent.com/533954/154665876-9252c72c-c42a-4a56-b6d1-0c6ba49f7140.png">

### Additional information

I didn't test it with Vue 3.x

**Comment by posva** [comment] 2022-02-18 16:01
Duplicate of https://github.com/vuejs/pinia/issues/852

**Closed as completed by posva** 2022-02-18 16:01 UTC
