### ISSUE TITLE
Pinia Init Action

### ISSUE THREAD

**Issue by shba007** [posva/pinia#1881] opened 2022-12-18 16:28 UTC
### What problem is this solving

When  useStore() called a init action should be called by default it will help to run some custom code which can be filling the state with data fetched from a server, And it should be called only when a store is installed

### Proposed solution

```
export const useWishlist = () => {
  const innerStore = defineStore('wishlist', {
    state: (): { isInit: boolean} => ({
      isInit: false,
    }),
    getters: {
    },
    actions: {
      async init() {
       if (process.server || this.isInit)
          return
        this.isInit = true

     // TODO: Code to run
    },
  });

  const store = innerStore();
  store.init()

  return store;
}
```

### Describe alternatives you've considered

- process.server is there because for Nuxt when SSR happens the isInit changes to true and init is async so it does not get updated
- If it is possible to hydrate the state from server side it will be more efficient ...but I am unable to done that 
- If I put isInit last init function will trigger multiple times if in a single page multiple component has same store

**Comment by posva** [comment] 2022-12-19 07:42
Duplicate of #1080

**Closed as not planned by posva** 2022-12-19 07:42 UTC
Labels: feature request

**Comment by Farnsi** [comment] 2023-05-17 10:01
@shba007 with your solution the TypeScript typings will not work when you use e.g. with `...mapState(uswWishList,`
The store itself will work.
