### ISSUE TITLE
dev pinia@"^2.0.30" from the root project

### ISSUE THREAD

**Issue by naihe138** [posva/pinia#2001] opened 2023-02-15 04:01 UTC
### Reproduction

npm error 

### Steps to reproduce the bug

1. package.json 
````js
"devDependencies": {
   "typescript": "^5.0.0-dev.20230214",
}
````
2. `npm install pinia` get a npm error like this:

````js
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: pinia@2.0.30
npm ERR!   dev pinia@"^2.0.30" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@">=4.4.4" from pinia@2.0.30
npm ERR!   node_modules/pinia
npm ERR!     dev pinia@"^2.0.30" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
````

### Expected behavior

no error

### Actual behavior

````js
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: pinia@2.0.30
npm ERR!   dev pinia@"^2.0.30" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@">=4.4.4" from pinia@2.0.30
npm ERR!   node_modules/pinia
npm ERR!     dev pinia@"^2.0.30" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
````

**Comment by posva** [comment] 2023-02-15 08:20
Duplicate of https://github.com/vuejs/pinia/issues/1969

**Comment by posva** [comment] 2023-02-15 08:20
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as not planned by posva** 2023-02-15 08:20 UTC
