### ISSUE TITLE
 @pinia/nuxt doesn't work with nuxt bridge

### ISSUE THREAD

**Issue by psycongaroo** [posva/pinia#917] opened 2021-12-22 08:22 UTC
### Actual behavior

`Cannot read properties of undefined (reading 'install') at Function.Vue.use (file://./.nuxt/dist/server/server.mjs:7842:23) at $id_c39524e4 (file://./.nuxt/dist/server/server.mjs:20715:7) at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:20913:3)`

### Additional information

The error popup only using vite and not webpack.
https://github.com/vuejs/pinia/issues/889

Using the method provided by @BobbieGoede is fixed:

`vite: {
    optimizeDeps: {
        exclude: ['pinia'],
    },
    resolve: {
        alias: {
            pinia: path.resolve(__dirname, './node_modules/pinia/dist/pinia.mjs'),
        },
    },
}`

**Comment by posva** [comment] 2021-12-22 08:40
Duplicate of https://github.com/vuejs/pinia/issues/690

**Comment by posva** [comment] 2021-12-22 08:40
For the moment, don't use Vite with Nuxt 2/bridge: https://github.com/piniajs/example-nuxt-bridge

**Closed as completed by posva** 2021-12-22 08:40 UTC
