### ISSUE TITLE
When I defineStore, if I use the same id as another Store, the data is not rendered to the page and no error is reported in the console.

### ISSUE THREAD

**Issue by hktcodingnow** [posva/pinia#2597] opened 2024-03-05 13:31 UTC
### Reproduction

When I define the same id as other stores in the store defineStore, the data is not rendered to the page and there is no error message in the console.

### Steps to reproduce the bug

![image](https://github.com/vuejs/pinia/assets/129660664/331aa7c7-2732-4766-9a60-3def8e79aa38)
I'm using the Pinia persistence plugin, and I've defined a store with an id of Data in another store's js, and this is causing the page data to not be rendered.
![屏幕截图 2024-03-05 212433](https://github.com/vuejs/pinia/assets/129660664/d3340697-29e2-426a-8ee8-0ecead8b8298)
When I changed the id to a unique id, the problem was solved.
![image](https://github.com/vuejs/pinia/assets/129660664/c75e9100-d3e5-487c-b2f3-3bea363bb21d)
![image](https://github.com/vuejs/pinia/assets/129660664/2ab1ec5b-43f1-4674-8d0d-0c53975ba384)

### Expected behavior

I'd like to be able to get relative bug feedback in the console when I run into a similar problem, rather than no error message at all, which is detrimental to my development.

### Actual behavior

When I defineStore, if I use the same id as another Store, the data is not rendered to the page and no error is reported in the console.I'd like to be able to get relative bug feedback in the console when I run into a similar problem, rather than no error message at all, which is detrimental to my development.

**Comment by posva** [comment] 2024-03-05 19:06
Duplicate of #1394

**Closed as not planned** 2024-03-05 19:06 UTC
