### ISSUE TITLE
npm i pinia 

### ISSUE THREAD

**Issue by message163** [posva/pinia#1870] opened 2022-12-12 13:01 UTC
### Reproduction

npm i pinia

### Steps to reproduce the bug

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: demo-3@0.0.0
npm ERR! Found: vue@3.2.45
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.37" from the root project
npm ERR!   peer vue@"^2.6.14 || ^3.2.0" from pinia@2.0.27
npm ERR!   node_modules/pinia
npm ERR!     pinia@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.4.0" from pinia@2.0.27
npm ERR!   node_modules/pinia
npm ERR!     pinia@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Expected behavior

normal setup  Why some small partners can install it but I can't

Can we solve this problem without -- force, or -- legacy peer deps

### Actual behavior

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: demo-3@0.0.0
npm ERR! Found: vue@3.2.45
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.37" from the root project
npm ERR!   peer vue@"^2.6.14 || ^3.2.0" from pinia@2.0.27
npm ERR!   node_modules/pinia
npm ERR!     pinia@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.4.0" from pinia@2.0.27
npm ERR!   node_modules/pinia
npm ERR!     pinia@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by message163** [comment] 2022-12-12 13:01
Can we solve this problem without -- force, or -- legacy peer deps

**Comment by posva** [comment] 2022-12-12 14:20
Duplicate of #853

**Comment by posva** [comment] 2022-12-12 14:21
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as not planned by posva** 2022-12-12 14:20 UTC
