### ISSUE TITLE
`mapState()` not working with Vue 3.4

### ISSUE THREAD

**Issue by balesniy** [posva/pinia#2551] opened 2024-01-14 16:04 UTC
### Reproduction

[old with vue 3.4.13](https://play.pinia.vuejs.org/#eNqNVE1v2zAM/SuCL0nRRGqRrocsCdIVPXSHbVh2m3dwbCZRa31AktMAgf/7KMlxvtoigGFIFPn4SEpvmzxoTdcVJMNkZHPDtZukkgutjCNbUll4VJV0YGZOGSA1WRglSIeyPJo7B84i0zOXOej51UPuuJK2jdBc8qzzNZWwCe4FLLKqxLBUEpIroSsHxTBuCaV0B9Y9odAjfzshd+fflfete/4vwK1UYXfxDUDD4T0ILnMDAvYwqcRvxNoW4MaB0CVSwB0hIz3ZbpEowpC6HjEdrfPKOSXJNC95/jpOkxY3TSbPu/WIRTcMGbEWNeklsXV9pEpfrJI4g8AfYcKBTZO2ojQJHfSWNGFhTcGK/tyoNwsG49MktMK7TnGgrIC1U6q0/UzzGLZyTtshY3kh0b+Akq8NleCY1IKdxUzv6Rd6y0o+Z5iIcVnA5jgNRvQLEJeg71ynN/T2jt4H1PWgARWnqJfSNTgNLhBZiemA3tHbASu4dYf2j5vkAdC4BtM3gDwMmEvznoQd5T45O8u/u204fmdzJRd8eTJ8/xp4CeanDtf36BJkZanevgebMxW0xeQryF/fsb/YTSzql4HA7KABLjNLwIvqj59mP2CD6/ZQqKIqm0F8cPgbrCorzzG6fatkgbQP/ALb53CXuVz+sU8bB9LuivJE9084DOTxk9L3dAd0cNDFRomos9jCVoxQX7iEY9WKGuTfdiNC2H7rzkRufBjcjWqDSteLVKxXpSHpXpHxhHQbSRiSG1JfhTqyKDot8VYRMKIxEeJW3NIQeX0dbbEJ/l+jICX1f3I65QM=)
[broken with 3.4.19](https://play.pinia.vuejs.org/#eNqNVE1v2zAM/SuCL0nRRGqRosOyJEhX9NAdtmHZbd7BsZlErfUBSU4DBP7voyTH+WqHAIYhUeTjIym9bfKgNV1XkAyTkc0N126SSi60Mo5sSWXhUVXSgZk5ZYDUZGGUIB3K8mjuHDiLTM9c5qDnVw+540raNkJzybPOl1TCJrgXsMiqEsNSSUiuhK4cFMO4JZTSHVj3hEKP/OmE3J2/V9637vm/ALdShd3FNwANh/cguMwNCNjDpBK/EWtbgBsHQpdIAXeEjPRku0WiCEPqesR0tM4r55Qk07zk+es4TVrcNJk879YjFt0wZMRa1KSXxNb1kSp9sUriDAJ/hAkHNk3aitIkdNBb0oSFNQUr+nOj3iwYjE+T0ArvOsWBsgLWTqnS9jPNY9jKOW2HjOWFRP8CSr42VIJjUgt2FjO9p/f0lpV8zjAR47KAzXEajOgXIC5B37lOb+jtHf0UUNeDBlScol5K1+A0uEBkJaYDekdvP7OCW3do/7hJHgCNazB9A8jDgLk070nYUe6Ts7P8u9uG43c2V3LBlyfD96+Bl2B+6HB9jy5BVpbq7VuwOVNBW0y+gvz1HfuL3cSifhoIzA4a4DKzBLyo/vhp9h02uG4PhSqqshnEB4e/wKqy8hyj29dKFkj7wC+wfQ53mcvlb/u0cSDtrihPdP+Ew0Ae/1P6nu6ADg662CgRdRZb2IoR6guXcKxaUYP8225ECNtv3ZnIjQ+Du1FtUOl6kYr1qjQk3SsynpBuIwlDckPqq1BHFkWnJd4qAkY0JkLcilsaIq+voy02wf9rFKSk/geXaOUR)

### Steps to reproduce the bug

click button

### Expected behavior

increment

### Actual behavior

nothing happens

### Additional information

Vue 3.4.12 or Composition API works fine

**Comment by posva** [comment] 2024-01-14 18:20
It seems related to https://github.com/vuejs/core/discussions/9974. Feel free to take a look and try to fix it

**Comment by balesniy** [comment] 2024-01-15 09:16
it looks more like related to vuejs/core#10082. it turns out that the problem is not related to pinia

**Comment by posva** [comment] 2024-01-25 10:40
Seems to be fixed upstream

**Comment by posva** [comment] 2024-02-23 09:16
It seems to be there again

**Comment by stephanfriedrich** [comment] 2024-05-21 07:26
Hello pinia team,
thank you very much for pinia.

will this problem still be ? or are there any descriptions on how to fix this problem yourself ?
it seems like not much is happening here anymore.

have a nice day

**Comment by Azurewarth0920** [comment] 2024-06-21 05:24
Tried to reproduced the bug.

Seems like it is broken with 3.4.13 and fixed in 3.4.14.

@balesniy Can you take a look at this?

**Comment by posva** [comment] 2024-09-26 09:11
[Fixed upstream](https://play.pinia.vuejs.org/#eNqNVF1v2jAU/StWXqAq2K3YuolRRFf1oXvYpnVvyx5CcgG38YdshyKh/Pdd2yEEaCekKHKu7zk+917nbJM7rem6gmScTGxuuHbTVHKhlXFkSyoL96qSDsyTUwZITRZGCdKjLI/hXidZZPrJZQ4GfnWXO66kbRGaS571vqQSNiG9gEVWlQhLJSG5ErpyUIzjJ6GU7sj6RxIG5E8vnN37e+Fz64F/C3ArVdgdviFoNLxFwWVuQMCeJpX4TFjbAvxwIHSJEvCLkImebrcoFGlIXU+YjtF55ZySZJaXPH+5TZOWN02mj7v1hMU0hExYy5oMkti6IUqlz1ZJnEHQjzRhw6ZJW1GahA76SJqwsKZgxXBu1KsFg/g0Ca3wqTMcKCtg7ZQq7TDTPMJWzmk7ZiwvJOYXUPK1oRIck1qwE8zsht7Qa1byOcODGJcFbA6PQcSwAHEO+y51dkWvP9BPgXU9akjFMeu5cg1OgwtkVmI2oh/pZ1Zw67rh93vk8RhcgxkaQBkGzLnHHsG6Rx9tnRy/u2s4fGdzJRd8eTR6/y/wEswPHS7vwRXIylK9fgsxZypoa8lXkL+8EX+2m1jTTwNBWad+l5kl4DX12w9P32GD63ZTqKIqmzG8s/kLrCorrzGmfa1kgbI7eUHtY7jJXC5/24eNA2l3RXmh+x84zOP+P6Xv5Y7oqNPFxoeos9jC1orQXbiEQ8+KDuT/7MaCsP3WnVjcbRfcj16DPjeIUqz3pDHpX5DbKek3hjAmV6S+CHVk0XJa4a0fIKIJEeJW3NKAvLyMsdgE/67RjpL6H4QU5K8=)

**Closed as completed by posva** 2024-09-26 09:11 UTC
Labels: bug, contribution welcome, upstream
