### ISSUE TITLE
hasInjectionContext error

### ISSUE THREAD

**Issue by LeanderY** [posva/pinia#2209] opened 2023-05-17 11:40 UTC
### Reproduction

RollupError

### Steps to reproduce the bug

![image](https://github.com/vuejs/pinia/assets/29173746/7108969b-5aaa-4434-bc2c-0a97e558b1da)

### Expected behavior

RollupError: "hasInjectionContext" is not exported by "node_modules/pinia/node_modules/vue-demi/lib/index.mjs", imported by "node_modules/pinia/dist/pinia.mjs".

### Actual behavior

RollupError: "hasInjectionContext" is not exported by "node_modules/pinia/node_modules/vue-demi/lib/index.mjs", imported by "node_modules/pinia/dist/pinia.mjs".

**Comment by posva** [comment] 2023-05-17 12:43
Duplicate of #2208 

Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as not planned by posva** 2023-05-17 12:43 UTC
