### ISSUE TITLE
Define Store for Typescript with decorators

### ISSUE THREAD

**Issue by kktos** [posva/pinia#1093] opened 2022-02-24 14:22 UTC
### What problem is this solving

When programming in Typescript, the modern way to augment a class is with decorators. That's very concise and readable.

### Proposed solution

A way could be to declare a class for the store and to decorate the class to have the state, actions and getters.
Here for a all-ion-one solution
```typescript
@PiniaStore("main")
class MainStore {
    counter: number= 0;
    name: string= 'Eduardo';

    get doubleCount(state): number {
        return state.counter * 2;
    }

    get doubleCountPlusOne(): number {
      return this.doubleCount * 2 + 1
    }

    reset() {
      this.counter = 0
    }
}
export const useMainStore = defineStore(MainStore);
```
or if we need more control over the process
```typescript
@PiniaStore("main")
class MainStore {
    @PiniaStoreStateProp("counter")
    counter: number= 0;
    @PiniaStoreStateProp("name")
    name: string= 'Eduardo';

    @PiniaStoreGet("double")
    get doubleCount(state): number {
        return state.counter * 2;
    }

    @PiniaStoreGet("doublePlusOne")
    get doubleCountPlusOne(): number {
      return this.doubleCount * 2 + 1
    }

    @PiniaStoreAction("reset")
    reset() {
      this.counter = 0
    }

    // internal method, not published in the store
    restart() {
      this.counter = Match.random();
    }

}
export const useMainStore = defineStore(MainStore);
```
but I'm not sure the more "talkative" version could be of any help....

**Comment by posva** [comment] 2022-03-06 22:52
Duplicate of https://github.com/vuejs/pinia/issues/802#issuecomment-971391517
I’m curious to see a working demo though and maybe even integrate it as an official plugin!

**Closed as completed by posva** 2022-03-06 22:52 UTC
Labels: feature request

**Comment by PentaTea** [comment] 2022-05-21 12:39
> Duplicate of [#802 (comment)](https://github.com/vuejs/pinia/issues/802#issuecomment-971391517) I’m curious to see a working demo though and maybe even integrate it as an official plugin!

I just used Pinia recently, but I still haven't found a reliable package to use decorator.

So I wrote one: https://www.npmjs.com/package/pinia-class-component
