### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'effect')

### ISSUE THREAD

**Issue by maxfrees** [posva/pinia#2853] opened 2024-12-07 15:52 UTC
### Reproduction

https://play.pinia.vuejs.org/#eNqNVN9v2jAQ/lesvBAmSFZ16iRGULeKh07aD7V9zIuJD+rOsS3boUyU/31nm4RAWVV4IL777rvvPnPZJl+1ztYNJJNkaivDtSMWXKOJoHJVlImzZTIrJa+1Mo5sSWPh3ikDZEeWRtVkkOWVaqQDkzk76AGtRz2oO1jaDqu55BRBpayUtNgpMBUdaTpsM1vCYNGsbpRc8hXWF32+NDwPv0SwEpAJtUp7BUgzzeM0qB0PDmotqAM8ETLVBmbbkw67ae7DvrAHTkZJHGhcU509WSXRp60nKfcJtGdCQsTHwoA+UiZ5eM7A1uOFUc8WDXpC8KiFXqPpOYO1U0rYMdU8lj06p+0kzysmEc9A8LXJJLhc6jp/VXN9lV1lF7ngixwb5Vwy2By3wYoxg/o97C30+mN28Sn7HFjXl3vS2rN60l0pd2iLs+g9OndiSqVqzQWYX9pxvJsjc6gQ6vl7iDnTQCexeoTqz5n4k91E1b8NoH1r6I3lqFmBi+n5/U/Y4HOXrBVrBKLfSN4B/m8arzHCvjWSoeweLqi9DXfM5erBzjcOpG2H8kKDGwEfbL55Y/SD3MvssufiYXXQwm51GCy5PFmzdnU6kIFll8TuYatKCZuQjkvU7WrRp0x9/wHVehC0p0NSzFqlsa6/GIVvlO7ThNhG+wYTsqTCtldFCEi6EMBOw+pZgtkHY2znt9Y/CHAEqkdq3C22pLKCyTwcbXsmL0Q2QqAC/9Mrq5WklZozjtN0xSSeH/5qyG7vMcaoUBIvhUHMtHQvBK86uMEO1P57mB9fgFELsiMmHRazzoAT0ZgmH/Czn+4Vz48zWlvKouM8N9F/mA2+nI0k294djY4ljc6xjfoz+cM5Ydgk3lGy+wcHkg9N

### Steps to reproduce the bug

I need to store some data in the store, but it is not ref type, also need to initialize null, but now the error, this is a big destructive update, I think you should set to? .effect, like some echarts or monaco editor examples, is not a ref and has to wait for some work to be done, so it starts out null or undefined, which I think the plugin should allow

### Expected behavior
![image](https://github.com/user-attachments/assets/384460e8-2375-4921-a5b7-4f0a41bca934)

### Actual behavior

I need to store some data in the store, but it is not ref type, also need to initialize null, but now the error, this is a big destructive update, I think you should set to? .effect, like some echarts or monaco editor examples, is not a ref and has to wait for some work to be done, so it starts out null or undefined, which I think the plugin should allow

### Additional information

I think it should be compatible with previous behavior, ref type or  change to ? .effect  https://github.com/vuejs/pinia/commit/67d31094784cc3bd256b0636b79dc8e421f6c3fb#diff-a4019455d4214f4ae04e5e463a0b67af62b68c0267b436ab16beeaaf45bc32d3R105

**Comment by posva** [comment] 2024-12-07 16:43
Duplicate of https://github.com/vuejs/pinia/issues/2848

**Closed as not planned by posva** 2024-12-07 16:43 UTC
