### ISSUE TITLE
shallowRef Vue Component inside store

### ISSUE THREAD

**Issue by JK-Effects** [posva/pinia#2458] opened 2023-10-22 10:09 UTC
### Reproduction

https://play.pinia.vuejs.org/#eNqVVlmP2zYQ/itTIUBs1JaS5njQHt00CNAWTVMkfciiLhpZpG3uyqJAUj6w8H/vR1KnpWybF1ucGc7xzXBmHoI3RRHuSh7EwaVOlSgMaW7KgrIkX18tAqMXwfUiF9tCKkMPpDdJlsn9R76iE62U3NIiwPVFcNER2ibFm9QImetWqBC5SPpipeZvZW74wbznefnJSMVr+adhlHrWfAteaPTT5mLnjvvMTW0jjIY8G1zXbEdi9JqXX+SXkYcDweNQQdMHhR+cRsZXSZkhoEVOlEqYyWFXx4hwxNXTzIptudlIZmXsiSgMwxa0yQgwM/prEciC5x3GIvh76rQRMaGLLDlWzMkTvoOtmN5LqHpnv6e1JSKzETo8U1XdmLVSRBFSUAXzj+KreCSaGYTocj6nvVT3mkQOMHa0lQz+LktDRqzXXGnaJyoX+Zoycc9RQnJPS44qam2dWWqrbDI0Om2sMsmhG6at5UJJVjoAnQOU5IzwvRIZn6cbJI7PFYwmTLdmWWKSGBWwPdbBkQe2gpXoNEXpuA9Hsr8nUPrVYfgW6BuOE9Flt8IiT2Ji57XcVFXtirpQDnQUVD99tvyI3E3cLa4/IFe1f/biZVR4tRH04usyahwIZoGv8znKKbzTMsfDdjldVAyUblN1zau0GGyMKXQcRdaR0NHtU7hDqah15M9cb+dLJfeaK+huUFoEN5CMkHojZabnSSH6KlOWQ57xTOxUmHMT5cU2Gty5eR2+Cp9HmVhGMBSJnPFD3wxuzBnf/h/ttejNs/D5y/B19D1UelxPyCBgMhqpWIn1GUi2EFEx6kPhnmIPLFeTvzqaUSVv3Eo3PL0fod/pg/f0D8UB2Q59peGZRK05Mm3Z7z797rLeMFG/ZQbpR5gfuZZZaX30Yj+VOYPbHTnn7S8u53h6f+p3BzweXQdlHa0LuoL27SOht+6+CF90UDxr0sCx6e5oiyLnva7enQJN+4QKbUZnwVVXx8TmpjWGQL132qDuY5pM6eq69ldhgqm87WXVxc8xPWsedkW77dJsZ4pplWS6TuKgM+VlllGi0V2OjYjvIkOObRQ1wkDPoBM2kFbmfbDHzEbgIumG0QTyJeMrdPMnD04krMM5FYcLMrIYcG7B+TLoW0SJny+NE+dDAF60E2PmfbRj5OEcBcR4UYWNTzTJs+nSE0ceK019euVgdcVq60jaY1+gjhpCPCySNf88yr9t+Ld9vhs7V67wG4atPZnxMJPryaiP0wvMGp8F3YLQRRZKMtkrXpTi42jYShkNfsionHYlORxE0ws8wfGVx+5z7VhSblwU1z/bpuDGByidsWGPjjS254A+2HScQkxcNOD6VL+D5ogQjgVK6sPyjqdm1pIrNRBFFBW1/vL/eDnOwXrI4tCP9Gsh2kFbaQTWCKHzztD+K1aaJVqD6RtJTd3NLdog27+WHGv7Pvuq3JNtRcamesvLRHpvr5+VSX29ch3ON3VCsbDu9epmEVBsAbbbAv5wxG7hg/ZrwOMZHVnqwe1u7J9sB5k9vrt3rzyyvduVut+sh/n89nKzcJSGs06J+bXZef7Vpdlnc+Zm+3kCPbWHsiV5gO1y3anJ3tLes/9fa/sw80PVsgSbudZRvyaZlgDPhEvJjmHCmOvKvwmNJ86VHYe2sKzDE1dw1eRoXplY0eQ710SeILCmP1oHfnSHRMBndzX0433asd42r0F3c7mstuPm+dbUr75fn28LuzuGti5ac1uRz/eCmU1MPzzDWOvSN1ysNybu0QuphQUd82fpFiF0x4q1lIpxBT3FgdYqORL4grXsJL1fK8DN5qnMJAT3GzG4PlcJEyVS/bxrdSkP6BEJs1vCK6hfZlDW+oQcYdOK6WVxcCBUGDQxB6d/Af9BPlM=

### Steps to reproduce the bug

This bug only happens in devMode.

Call the openContextMenu Function inside the store and pass a component as shallowRef.

### Expected behavior

The component should be displayed in the UI.

### Actual behavior

The devtools show a null value for the component_ref variable inside the store variable.
The passed Component does not get displayed.

Sometimes the content is also displayed when I change a file and the app partially reloads.
If I pass the component directly, everything works. (The console warns against direct passing).

### Additional information

This Issue with Code can be seen in the discussion: #2449 

I am building a custom ContextMenu for which I am saving the state in pinia. So that I can display content in my ContextMenu, I am passing a Vue component as shallowref to the store.

In dev mode, pinia displays the component_ref state-variable as a null value in the dev tools. Even if I output the value in the UI, nothing is displayed. When I output the values in the openContextMenu function via the console, I do not get null values.
This happens when I pass a shallowRef component. If I pass the component directly, everything works. (The console warns against direct passing).
Sometimes the content is also displayed when I change a file and the app partially reloads.
If I build the application for production and then test it, shallowref works without problems.

**Comment by posva** [comment] 2023-10-22 13:18
Duplicate of https://github.com/vuejs/pinia/discussions/2449

**Comment by posva** [comment] 2023-10-22 13:18
Let's keep this in the discussion, it's still a usage question after all: not sure what you are intended to do with template refs: https://vuejs.org/guide/essentials/template-refs.html

**Closed as not planned** 2023-10-22 13:21 UTC
