### ISSUE TITLE
Pinia/nuxt 0.7.0 fails to load

### ISSUE THREAD

**Issue by peterh-capella** [posva/pinia#2832] opened 2024-11-12 16:59 UTC
### Reproduction

See steps below

### Steps to reproduce the bug

1. Run `npx nuxi@latest init test-project` Choose default options. `cd test-project`
2. Run `npx nuxi@latest modules add pinia`
3. Run `npm run dev`

### Expected behavior

Nuxt "Welcome" application loads.

### Actual behavior

500 error with message:

```
[vite-node] [ERR_LOAD_URL] pinia
at pinia
```

### Additional information

Removing the `modules: ['@pinia/nuxt']` from `nuxt.config.ts` and relaunching the application loads the Welcome app as expected.

**Comment by posva** [comment] 2024-11-12 18:55
Duplicate of https://github.com/vuejs/pinia/issues/2822

**Comment by posva** [comment] 2024-11-12 18:55
See https://github.com/vuejs/pinia/issues/2822#issuecomment-2456507133 for solutions

**Closed as not planned by posva** 2024-11-12 18:55 UTC
