### ISSUE TITLE
How do we keep the state some module's data after refresh

### ISSUE THREAD

**Issue by shuperry** [posva/pinia#459] opened 2021-04-28 09:13 UTC
With vuex, there is a npm package named vuex-persistedstate to storage state automatic, with some configuration of cause.

How do we do the same thing with pinia, this function will be very useful.

**Comment by posva** [comment] 2021-04-28 09:41
Duplicate of https://github.com/posva/pinia/issues/309#issuecomment-740574516

**Closed as completed by posva** 2021-04-28 09:41 UTC
Labels: feature request
