### ISSUE TITLE
pina and vue-router 4 seems not work on a single file

### ISSUE THREAD

**Issue by Seyid-cmd** [posva/pinia#954] opened 2022-01-12 08:35 UTC
### Discussed in https://github.com/vuejs/pinia/discussions/951

<div type='discussions-op-text'>

<sup>Originally posted by **Seyid-cmd** January 11, 2022</sup>

```
import { defineStore, acceptHMRUpdate } from "pinia";
```

I am using pinia and vue-router 4.x ,but i am having a problem using both of them in a store.
each works independently ,but not together.

If i use 
```
import router from '../router'
```

 router will work but pinia is not with  error 
```
Uncaught ReferenceError: Cannot access 'useAuthStore' before initialization
at axiosroot.ts
--- 
@line let authStore = useAuthStore(pinia);
```
//here is axiosroot.ts

```

import axios from "axios";
import {useAuthStore} from '../stores/auth-store'
import { createPinia } from "pinia";
 const pinia=createPinia();
let authStore = useAuthStore(pinia);
const url = "http://127.0.0.1:8000/api";
const   myToken =authStore.getToken;
export default axios.create({
  url,
  headers:{"Accept":"application/json"},
  
});



```

When i import router from vue-router
useRouter is undefined
```
import {useRouter} from 'vue-router'
const router =useRouter();
```
the error 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'push') 
--- 
error @ line router.push({name:'Login'})
```

// here is the remainning  relavant code
 
export const useAuthStore = defineStore({
  id: "user",
  state: () => ({
    token: localStorage.getItem('token'),
    logInStatus:!!localStorage.getItem('token')
  }),

  actions: {

    LogOut(payload: any) {
      // this.DELETE_TOKEN();
      // this.UPDATE_LOGIN_STATUS(false);
      myrouter.push({name:'Login'})

    },
  },
});

if (import.meta.hot) {
  import.meta.hot.accept(acceptHMRUpdate(useAuthStore, import.meta.hot));
}
</div>

**Comment by posva** [comment] 2022-01-12 12:53
Duplicate of https://github.com/vuejs/pinia/discussions/951

**Closed as completed by posva** 2022-01-12 12:53 UTC
