### ISSUE TITLE
Ability to access store context when using composable stores

### ISSUE THREAD

**Issue by Fl0r14n** [posva/pinia#2043] opened 2023-03-01 16:05 UTC
### What problem is this solving

There is no way to access the plugins when defining stores using composable stores, though they are present when using the store

### Proposed solution

const pinia = createPinia().use(({ store }) => {
  store.router = markRaw(router)
})

const useMyStore = defineStore('MyStore', storeContext => {
  const {router} = storeContext
  console.log(router) 
  return {router}
})

**Comment by posva** [comment] 2023-03-01 16:41
Duplicate of #1784

**Closed as not planned by posva** 2023-03-01 16:41 UTC
Labels: feature request
