### ISSUE TITLE
fix npm module to support nuxt3

### ISSUE THREAD

**Issue by buddudevelopers** [posva/pinia#1389] opened 2022-06-22 23:19 UTC
### Reproduction

Reproduction

### Steps to reproduce the bug

1. ```npm i @pinia/nuxt```
2. You get the error ```dr@drlaptop:~/projects/serverside/nuxtfrontend$ npm i @pinia/nuxt
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.2.37
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.37" from @nuxt/vite-builder@3.0.0-rc.4
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     @nuxt/vite-builder@"^3.0.0-rc.4" from nuxt@3.0.0-rc.4
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"3.0.0-rc.4" from the root project
npm ERR!   peer vue@"^3.2.25" from @vitejs/plugin-vue@2.3.3
npm ERR!   node_modules/@vitejs/plugin-vue
npm ERR!     @vitejs/plugin-vue@"^2.3.3" from @nuxt/vite-builder@3.0.0-rc.4
npm ERR!     node_modules/@nuxt/vite-builder
npm ERR!       @nuxt/vite-builder@"^3.0.0-rc.4" from nuxt@3.0.0-rc.4
npm ERR!       node_modules/nuxt
npm ERR!         dev nuxt@"3.0.0-rc.4" from the root project
npm ERR!   4 more (@vue/server-renderer, @vueuse/head, nuxt, vue-router)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @pinia/nuxt@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 3" from @vue/composition-api@1.6.2
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.14
npm ERR!     node_modules/pinia
npm ERR!       peer pinia@">=2.0.14" from @pinia/nuxt@0.1.9
npm ERR!       node_modules/@pinia/nuxt
npm ERR!         @pinia/nuxt@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/dr/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dr/.npm/_logs/2022-06-22T23_12_59_843Z-debug-0.log
```

### Expected behavior

expected to install module without issues

### Actual behavior

Errors out demanding for vue2

### Additional information

None

**Comment by posva** [comment] 2022-06-23 06:04
Duplicate of #853

**Comment by posva** [comment] 2022-06-23 06:04
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as not planned by posva** 2022-06-23 06:04 UTC
