### ISSUE TITLE
TypeScript errors with `vue-tsc --noEmit`

### ISSUE THREAD

**Issue by Shinigami92** [posva/pinia#763] opened 2021-11-03 13:29 UTC
### Reproduction

_On demand_

### Steps to reproduce the behavior

1. Create a **Vue2** project
2. Setup a store / use `pinia`
3. Run `yarn vue-tsc --noEmit`

### Expected behavior

No compile time TS errors

### Actual behavior

```node
$ yarn vue-tsc --noEmit
node_modules/pinia/dist/pinia.d.ts:3:10 - error TS2305: Module '"vue-demi"' has no exported member 'DebuggerEvent'.

3 import { DebuggerEvent } from 'vue-demi';
           ~~~~~~~~~~~~~

node_modules/pinia/dist/pinia.d.ts:5:10 - error TS2305: Module '"vue-demi"' has no exported member 'Plugin'.

5 import { Plugin as Plugin_2 } from 'vue-demi';
           ~~~~~~

node_modules/pinia/dist/pinia.d.ts:516:42 - error TS2315: Type 'App' is not generic.

516 export declare const PiniaPlugin: ((app: App<any>, ...options: any[]) => any) & {
                                             ~~~~~~~~

node_modules/pinia/dist/pinia.d.ts:517:22 - error TS2315: Type 'App' is not generic.

517     install?: ((app: App<any>, ...options: any[]) => any) | undefined;
                         ~~~~~~~~


Found 4 errors.
```

**Comment by posva** [comment] 2021-11-03 13:49
Duplicate of https://github.com/posva/pinia/issues/758

**Closed as completed by posva** 2021-11-03 13:49 UTC

**Comment by Shinigami92** [comment] 2021-11-03 14:09
Much more type-safe solution for me is using `yarn patch`

```diff
diff --git a/dist/pinia.d.ts b/dist/pinia.d.ts
index 947b13cfe11c851358d9ef3cc8b97100f3db31b6..88fabc1da4a9c6ef9f8007836941448b253d4df7 100644
--- a/dist/pinia.d.ts
+++ b/dist/pinia.d.ts
@@ -1,7 +1,9 @@
 import { App } from 'vue-demi';
 import { ComputedRef } from 'vue-demi';
+// @ts-ignore
 import { DebuggerEvent } from 'vue-demi';
 import { EffectScope } from 'vue-demi';
+// @ts-ignore
 import { Plugin as Plugin_2 } from 'vue-demi';
 import { Ref } from 'vue-demi';
 import { ToRefs } from 'vue-demi';
@@ -513,7 +515,9 @@ export declare interface PiniaCustomStateProperties<S extends StateTree = StateT
 /**
  * @deprecated use `PiniaVuePlugin` instead.
  */
+// @ts-ignore
 export declare const PiniaPlugin: ((app: App<any>, ...options: any[]) => any) & {
+    // @ts-ignore
     install?: ((app: App<any>, ...options: any[]) => any) | undefined;
 };
```

**Comment by posva** [comment] 2021-11-03 15:07
Adapting this requires a few changes:

- https://github.com/vueuse/vue-demi/pull/115
- https://github.com/vuejs/composition-api/pull/845
- In Pinia: ee358a6

**Comment by Shinigami92** [comment] 2021-11-03 15:12
Patch for `2.0.1`

```diff
diff --git a/dist/pinia.d.ts b/dist/pinia.d.ts
index e0b5f993dc45072df1d0a8ad110d22785d8d663d..6f8ca69c1221566998f4d5040bf53a08d0432355 100644
--- a/dist/pinia.d.ts
+++ b/dist/pinia.d.ts
@@ -1,7 +1,9 @@
 import { App } from 'vue-demi';
 import { ComputedRef } from 'vue-demi';
+// @ts-ignore
 import { DebuggerEvent } from 'vue-demi';
 import { EffectScope } from 'vue-demi';
+// @ts-ignore
 import { Plugin as Plugin_2 } from 'vue-demi';
 import { Ref } from 'vue-demi';
 import { ToRefs } from 'vue-demi';
```

---

Maybe I could look into that later if I have some time, but not sure.
For now I use the local patch, cause in the long run we switch to pinia cause we want to migrate to Vue 3 anyways someday

**Comment by Shinigami92** [comment] 2021-11-04 13:58
Updated to 2.0.2 and everything is working now without patch
Thx :tada:

**Comment by posva** [comment] 2021-11-04 15:00
Nice! 💪
