### ISSUE TITLE
Unable to use Pinia w/ Nuxt3

### ISSUE THREAD

**Issue by lucavenir** [posva/pinia#1536] opened 2022-08-10 09:08 UTC
### Reproduction

https://github.com/lucavenir/nuxt3-pinia-repro

### Steps to reproduce the bug

I actually think there's something wrong in the installation process of Pinia on Nuxt3, or at least it needs more documentation.

I'm reading [this page](https://pinia.vuejs.org/getting-started.html), that says:

> npm install pinia
> [...]
> If you are using Nuxt, you should follow [these instructions](https://pinia.vuejs.org/ssr/nuxt.html).

But just the first install results in an error. Here's the repro steps:

1. `npx nuxi init .`
2. `npm install`
3. `npm run dev`
4. `npm install pinia`

The last command outputs: 

<details>

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.2.37
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.37" from @nuxt/vite-builder@3.0.0-rc.6
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     @nuxt/vite-builder@"^3.0.0-rc.6" from nuxt@3.0.0-rc.6
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"3.0.0-rc.6" from the root project
npm ERR!   peer vue@"^3.2.25" from @vitejs/plugin-vue@2.3.3
npm ERR!   node_modules/@vitejs/plugin-vue
npm ERR!     @vitejs/plugin-vue@"^2.3.3" from @nuxt/vite-builder@3.0.0-rc.6
npm ERR!     node_modules/@nuxt/vite-builder
npm ERR!       @nuxt/vite-builder@"^3.0.0-rc.6" from nuxt@3.0.0-rc.6
npm ERR!       node_modules/nuxt
npm ERR!         dev nuxt@"3.0.0-rc.6" from the root project
npm ERR!   5 more (@vue/server-renderer, @vueuse/head, nuxt, vue-demi, vue-router)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! pinia@"^2.0.17" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.17
npm ERR!     node_modules/pinia
npm ERR!       pinia@"^2.0.17" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-08-10T08_25_15_812Z-debug-0.log
```

</details>

Maybe I _wasn't_ supposed to `npm install pinia` _before_ following [these instructions](https://pinia.vuejs.org/ssr/nuxt.html) about Nuxt3 (if so, the documentation page should be more clear about this, imo).

Anyways, such instructions say:

> npm install @pinia/nuxt
> Add `'@pinia/nuxt'` to the modules inside `nuxt.config.ts`.

I can see that these two steps won't result in any `npm install` errors, but I can't use `defineStore` as the module `pinia` is not found, nor `defineStore` can be found inside `pinia@nuxt` (why doesn't `@pinia/nuxt` expose a `defineStore` method, directly?).

VSCode intellisense comes to the rescue as I try to define a store without explicitly importing `defineStore` myself. Here's what is auto-imported:

`import { defineStore } from "@pinia/nuxt/dist/runtime/composables";`

So it looks like I am able to define my first `counterStore` and to use it inside a dummy page.

But when I try and `npm run dev` I get the following errors:

<details>
 ERROR  Missing "./dist/runtime/composables" export in "@pinia/nuxt" package                                                                                                                                               10:54:53

ℹ Vite client warmed up in 459ms                                                                                                                                                                                           10:54:53

 ERROR  Missing "./dist/runtime/composables" export in "@pinia/nuxt" package                                                                                                                                               10:54:53

ℹ Vite server warmed up in 288ms                                                                                                                                                                                           10:54:53

 WARN  [SSR] Error transforming /home/[...]/nuxt3-pinia-repro/composables/useCounter.ts: Missing "./dist/runtime/composables" export in "@pinia/nuxt" package                                              10:54:54

  at bail (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:38597:8)
  at resolve (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:38674:10)
  at resolveExports (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:40982:12)
  at resolveDeepImport (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:41000:31)
  at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:40773:20)
  at Context.resolveId (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:40581:28)
  at Object.resolveId (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:39254:55)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async TransformContext.resolve (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:39028:23)
  at async normalizeUrl (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:58348:34)
</details>

At this point I'm lost and I feel like I can't / won't use `pinia` in Nuxt3 at the moment.

I tried and searched some answers on the web, and indeed I did find this [example](https://stackblitz.com/github/piniajs/example-nuxt-3?file=stores%2Fcounter.ts), but that shows _both_ `pinia` _and_ `@pinia/nuxt` installed inside `package.json`. I am unable to reproduce that example as it results in the conflict error.

At some point I tried and searched / read the repo here for usage of `usePinia` (maybe it should be called before defining the store?), but I found nothing.

I tried to read code and tests inside this repo about `pinia` being used in Nuxt3, but I still found nothing.

I'm opening this issue as I find necessary to document better the installation process on Nuxt3. I'd like to help too, if I only knew how to actually make this work.

### Expected behavior

Being able to define a store in Nuxt3, without breaking a sweat, as I'd do in Vue3.

### Actual behavior

Can't install `pinia` and / or can't use `@pinia/nuxt` in a way that's accepted by the framework or at least documented.

### Additional information

This was a [question](https://github.com/vuejs/pinia/discussions/1533), but as I found reproducibility, I moved this here.

**Comment by posva** [comment] 2022-08-10 09:50
Duplicate of #853

**Comment by posva** [comment] 2022-08-10 09:50
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as not planned by posva** 2022-08-10 09:50 UTC
