### ISSUE TITLE
2.1.0 错误

### ISSUE THREAD

**Issue by trry-hub** [posva/pinia#2207] opened 2023-05-17 10:31 UTC
### Reproduction

2.1.0

### Steps to reproduce the bug

![image](https://github.com/vuejs/pinia/assets/67309192/1ad4282a-dff5-4b7e-95f1-29b63f1260ec)

### Expected behavior

![image](https://github.com/vuejs/pinia/assets/67309192/2dcefd45-a7c0-488e-8be1-d64b19918c22)

### Actual behavior

![image](https://github.com/vuejs/pinia/assets/67309192/f04ad199-7ed4-4750-8fb4-8ad700e091f9)

**Comment by posva** [comment] 2023-05-17 12:42
Duplicate of #2208

**Closed as not planned by posva** 2023-05-17 12:42 UTC
