### ISSUE TITLE
The doc is blinking between light and dark

### ISSUE THREAD

**Issue by Clarkkkk** [posva/pinia#875] opened 2021-12-04 17:30 UTC
### Reproduction

The document website is blinking between light and dark when there are two or more tabs of it.

![bug](https://user-images.githubusercontent.com/66827108/144718644-fdcb8ce8-1a86-4f3c-a7e3-e627253c3beb.GIF)

### Steps to reproduce the behavior

Open two or three tabs of https://pinia.esm.dev/ in the browser (at night) and then wait.

### Additional information

Browser: the latest version Chrome or Firefox
OS: Windows 11 (in light theme)

**Comment by posva** [comment] 2021-12-04 17:33
Duplicate of #686

**Closed as completed by posva** 2021-12-04 17:33 UTC
