### ISSUE TITLE
Cannot install with latest @nuxtjs/composition-api

### ISSUE THREAD

**Issue by phanect** [posva/pinia#1437] opened 2022-07-08 23:54 UTC
### Reproduction

https://github.com/phanect/repro-pinia-nuxt-composition-api

### Steps to reproduce the bug

1. Run `npm init` to generate package.json
2. Run `npm install pinia @nuxtjs/composition-api`

### Expected behavior

`npm install` successfully install `pinia` and `@nuxt/composition-api`

### Actual behavior

`npm install` failed and the following output is shown:

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: repro-pinia-nuxt-composition-api@1.0.0
npm ERR! Found: vue@2.7.4
npm ERR! node_modules/vue
npm ERR!   peer vue@"^2.7.4" from @nuxtjs/composition-api@0.33.0
npm ERR!   node_modules/@nuxtjs/composition-api
npm ERR!     @nuxtjs/composition-api@"0.33.0" from the root project
npm ERR!   vue@"^2.6.12" from @nuxt/vue-app@2.15.8
npm ERR!   node_modules/@nuxt/vue-app
npm ERR!     peer @nuxt/vue-app@"^2.15" from @nuxtjs/composition-api@0.33.0
npm ERR!     node_modules/@nuxtjs/composition-api
npm ERR!       @nuxtjs/composition-api@"0.33.0" from the root project
npm ERR!     @nuxt/vue-app@"2.15.8" from nuxt@2.15.8
npm ERR!     node_modules/nuxt
npm ERR!       peer nuxt@"^2.15" from @nuxtjs/composition-api@0.33.0
npm ERR!       node_modules/@nuxtjs/composition-api
npm ERR!         @nuxtjs/composition-api@"0.33.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! pinia@"2.0.14" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.14
npm ERR!     node_modules/pinia
npm ERR!       pinia@"2.0.14" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/phanect/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phanect/.npm/_logs/2022-07-08T23_38_19_822Z-debug-0.log
```

### Additional information

Pinia has a [peerDependency for `@vue/composition-api`](https://github.com/vuejs/pinia/blob/v2/packages/pinia/package.json#L79), but [latest `@nuxt/composition-api` requires Vue 2.7](https://github.com/nuxt-community/composition-api/blob/main/package.json#L110) and [`@vue/composition-api` does not support Vue 2.7](https://github.com/vuejs/composition-api/blob/main/package.json#L54).
These peerDependencies might be the cause of this conflict.

[Pinia's peerDependency for `@vue/composition-api` is marked optional](https://github.com/vuejs/pinia/blob/v2/packages/pinia/package.json#L87-L89), but I guess it's not working as expected.

Workaround: `npm install --legacy-peer-deps pinia @nuxtjs/composition-api`

**Comment by posva** [comment] 2022-07-09 08:56
Duplicate of https://github.com/vuejs/pinia/issues/853

**Closed as completed by posva** 2022-07-09 08:56 UTC
