### ISSUE TITLE
Production build targeting IE11 contains ES6 syntax

### ISSUE THREAD

**Issue by Ilanaya** [posva/pinia#1971] opened 2023-02-01 10:41 UTC
### Reproduction

https://github.com/maIIady/pinia-ie-reproduction

### Steps to reproduce the bug

1. clone repo
2. npm i -> npm run build -> npx serve ./dist
3. Try opening production build in IE11 and check errors

### Expected behavior

There is no unsupported syntax in `pinia.prod.cjs` 
![image](https://user-images.githubusercontent.com/74474615/216015566-a7f0bd4d-eda1-4ab1-beb9-7ef3e6881eb3.png)

### Actual behavior

Opening production build fails in IE11

### Additional information

Reproduction repo also contains workarounds about https://github.com/vuejs/pinia/issues/1143. Production build will also fail if devtools are bundled.
This issue resolves with manual traspilation of `node_modules/pinia` with babel-loader (as I did in project I'm currently working on). However I didn't find a way to make it work in IE even with `transpileDependencies: true` in `vue.config.js` in reproduction example.

Is there a way to remove ES6 syntax from pinia production build or I have to manually transpile it with babel?

PS. Gonna gladly open a PR if you provide some information about possibe fixes

**Comment by posva** [comment] 2023-02-01 13:04
Duplicate of #1143

**Comment by posva** [comment] 2023-02-01 13:05
I released a new version with the fix of the spread operator in devtools code but note IE11 is not targeted as a supported versions of the devtools code, only of the production build.

**Closed as not planned by posva** 2023-02-01 13:05 UTC

**Comment by Ilanaya** [comment] 2023-02-01 14:09
@posva Sorry, I might misunderstand you, but my report is primarily about this code presenting in `pinia.prod.cjs`. 
![image](https://user-images.githubusercontent.com/74474615/216061352-c79cc324-f196-4ca3-9b23-a487c6a7046f.png)

As I can see, this code in not related to devtools and contains syntax which IE simply won't understand without transpilation. Am I supposed to transpile it myself or I just miss smth?

**Comment by posva** [comment] 2023-02-01 18:37
Ah i see. Yeah, given the state of IE, you will have to transpile pinia to use it with IE11

**Comment by mazy-n** [comment] 2023-02-08 03:22
@posva Is there any expectation to fix it ？Including the production environment to build @vue/devtools-api

**Comment by posva** [comment] 2023-02-08 07:29
The version including the devtools is not expected to work with ie. You will have to transpile.
