### ISSUE TITLE
Support $patch from setup stores (composition API) via a macro or a composable function

### ISSUE THREAD

**Issue by segevfiner** [posva/pinia#1590] opened 2022-08-24 15:49 UTC
### What problem is this solving

It's useful to be able to access `$patch` from pinia actions, but currently to use it with setup stores, composition API you have to grab it via `this`:
```ts
import { ref } from "vue";
import { defineStore, type Store } from "pinia";

const useStuffStore = defineStore("stuff", () => {
  const stuff1 = ref({});
  const stuff2 = ref({});

  async function doStuff(this: Store) {
    const result = await asyncStuffGoesBrrr();
    this.$patch({
      stuff1: result.stuff1,
      stuff2: result.stuff2,
    });
  }

  return {
    stuff1,
    stuff2,
    doStuff,
});
```

You have to manually type `this`, but it isn't the full correct type for the store which causes type checking issues. In addition, you can't do this when using `watch`/`watchEffect` and friends as you won't have `this` there.

### Proposed solution

Add a compiler macro or an composition style imported function that allows to patch the current store for setup stores:
```ts
import { ref } from "vue";
import { defineStore, patch } from "pinia";

const useStuffStore = defineStore("stuff", () => {
  const stuff1 = ref({});
  const stuff2 = ref({});

  watchEffect((onCleanup) => {
    patch(/* ... */);
    
    onCleanup(() => {
      patch(/* ... */);
    });
  });

  async function doStuff(this: Store) {
    const result = await asyncStuffGoesBrrr();
    patch({
      stuff1: result.stuff1,
      stuff2: result.stuff2,
    });
  }

  return {
    stuff1,
    stuff2,
    doStuff,
});
```

Or a variety of this thereof, such as `usePatch` that returns a patch function or `useSelf` that returns the store object of the store itself.

### Describe alternatives you've considered

Not using `patch`, which will cause a lot of unnecessary additional updates of reactive dependencies, harming performance.

**Comment by posva** [comment] 2022-08-24 17:36
Duplicate of https://github.com/vuejs/pinia/discussions/1509

**Comment by posva** [comment] 2022-08-24 17:37
> Not using patch, which will cause a lot of unnecessary additional updates of reactive dependencies, harming performance.

Btw this is not true in Vue, so you don’t need to worry about changes multiple things one after the other. There will always be one render :)

**Closed as not planned by posva** 2022-08-24 17:36 UTC
Labels: feature request

**Comment by segevfiner** [comment] 2022-08-24 18:26
@posva What do you mean? Should we just skip using `$patch`? Is it something that's not really needed and as such there is no need to add support for it to setup stores?
