### ISSUE TITLE
Pinia is not injected before vue-router beforeEach

### ISSUE THREAD

**Issue by BenShelton** [posva/pinia#1436] opened 2022-07-08 14:39 UTC
### Reproduction

https://stackblitz.com/edit/github-ddb6tb?file=src/main.ts

### Steps to reproduce the bug

1. Install Pinia & Vue Router
2. Add a `beforeEach` on the router instance that uses a store
3. Check console on startup

### Expected behavior

No warnings appear

### Actual behavior

Warning about injection symbol appears. See screenshot (the `toRefs` warning appears unrelated):

<img width="547" alt="Screenshot 2022-07-08 at 14 42 02" src="https://user-images.githubusercontent.com/22983604/178003647-dfbc88be-7f8f-4b14-9762-ce5b025ef003.png">

### Additional information

This is a minimal example of what we have already had running for a long time in production. Since upgrading to Vue 2.7 this warning has started to appear with no other code changes.

Workaround is adding an `await nextTick()` in the start of the router guard which makes the error disappear.

**Comment by posva** [comment] 2022-07-08 16:21
Duplicate of https://github.com/vuejs/vue/issues/12636

**Closed as completed by posva** 2022-07-08 16:21 UTC
