### ISSUE TITLE
State seems to not propagate abstract properties of classes

### ISSUE THREAD

**Issue by Zsapi** [posva/pinia#1655] opened 2022-09-15 14:14 UTC
### Reproduction

https://stackblitz.com/edit/vitejs-vite-33awpd?file=src/store/index.ts

### Steps to reproduce the bug

1. Open reproduction
2. Wait for error to appear on line 26

### Expected behavior

this.op in method1 should be of type Operation, and method2 should accept is as a parameter.

### Actual behavior

this.op seems to have lost it's protected abstract functions, so method2 is not accepting it as an Operation type parameter.

### Additional information

I suspect there's a bug somewhere in the state's type inference where the types loose their protected abstract properties.
I've tested this setup with plain typescript, and it worked correctly for this use case. 
Thanks in advance for your help. (I hope it's not me messing up something trivial 😅   )
Update: I've tried changing the functions from protected to public, and it seems to work that way, but I think it should work with protected as well.

**Comment by posva** [comment] 2022-09-15 18:50
Duplicate of https://github.com/vuejs/core/issues/2981

**Closed as not planned by posva** 2022-09-15 18:50 UTC
