### ISSUE TITLE
State typing doesn't work with classes with private attributes/methods

### ISSUE THREAD

**Issue by hugoattal** [posva/pinia#871] opened 2021-12-03 16:30 UTC
### Reproduction

Here is a little example
```ts
import { defineStore } from "pinia";

// This is a class called "Thing" with a private attribute name
class Thing {
    private readonly name: string;

    constructor(name: string) {
        this.name = name;
    }

    getName(): string {
        return this.name;
    }
}

// This function expects a Thing as argument
function displayName(thing: Thing) {
    console.log(thing.getName());
}

// This little example works as intended
const a: Thing = new Thing("test");
displayName(a);

export const useTestStore = defineStore({
    id: `test`,
    actions: {
        getThingName() {
            // Error TS2345
            displayName(this.thing);
        }
    },
    state: () => ({
        thing: new Thing("test")
    })
});
```

![image](https://user-images.githubusercontent.com/4563971/144637059-49ef4b05-87be-4485-846c-60fe7f33e4c3.png)

### Steps to reproduce the behavior

Just paste this code in WebStorm (last version)

### Expected behavior

It should pass typescript compilation

### Actual behavior

Typescript fire a TS2345 error because property "name" is missing

### Additional information

It can be "fixed" this by forcing the type:
![image](https://user-images.githubusercontent.com/4563971/144637180-ce6f5d19-d237-4443-92cf-8b66ed780f26.png)

Also, it's rather a small bug, I just wanted to mention it if anyone encountered this. I ❤️ 🍍 !

**Comment by posva** [comment] 2021-12-03 17:10
Duplicate of https://github.com/vuejs/vue-next/issues/2981

**Comment by posva** [comment] 2021-12-03 17:12
Pinia unwraps any property passed in the state and the resulting type is also unwrapped with `UnwrapRef`. For the moment, you need to manually cast it:

```js
      displayName(this.thing as Thing)
```

**Closed as completed** 2021-12-03 17:12 UTC
