### ISSUE TITLE
Using empty state 

### ISSUE THREAD

**Issue by Xexnon** [posva/pinia#882] opened 2021-12-07 07:52 UTC
### Reproduction

Initialising and empty state then adding data but the getters still returns null after the state has been populated

### Steps to reproduce the behavior

```
export const useLogin = defineStore('login_info', {
  state: () => ({
    
  } as any),
  getters: {
    getUserId: (state) => state.userId
  },
  actions: {
    setUser (params: any) {
      this.$state = {
        ...params
      }
    }
  },
  persist: true
})
```

```
setup () {
  const login = useLogin()
  function addUser () {
    login.setUser({
      name: 'fdd',
      userId: 1
      ...somuchdata
    })
  }
  console.log(login.$state.userId)
  console.log(login.getUserId)
  const user = computed(() => login.getUserId)
  console.log(user.value)
  addUser()
  return {
    login,
    user
  }
}
```

### Expected behavior
`login.$state.userId` returns the state
`login.getUserId` returns the state
`const user = computed(() => login.getUserId)` returns the state

### Actual behavior
`login.$state.userId` returns the state
`login.getUserId` returns null
`const user = computed(() => login.getUserId)` returns null

A clear and concise description of what actually happens.

### Additional information

```
export const useLogin = defineStore('login_info', {
  state: () => ({
    user: {}
  } as any),
  getters: {
    getUserId: (state) => state.user.userId || null
  },
  actions: {
    setUser (params: any) {
      this.$state.user = {
        ...params
      }
    }
  },
  persist: true
})
```
if i do this 

### Expected behavior
`login.$state.userId` returns the state
`login.getUserId` returns the state
`const user = computed(() => login.getUserId)` returns the state

### Actual behavior
`login.$state.userId` returns the state
`login.getUserId` returns the state
`const user = computed(() => login.getUserId)` returns the state

I need an empty state initialised or the only way is the second approach

the reason why i need an empty state is because i dont know the type of data coming from the api

**Comment by posva** [comment] 2021-12-07 10:31
Duplicate of https://github.com/posva/pinia/issues/881

**Comment by posva** [comment] 2021-12-07 10:31
Don't open duplicates on purpose or I will have to block you, thanks.

**Closed as completed by posva** 2021-12-07 10:31 UTC
