### ISSUE TITLE
Invalid Vue App Instance Type Thrown When Use In Pinia Store Action

### ISSUE THREAD

**Issue by lostncg** [posva/pinia#2036] opened 2023-03-01 00:46 UTC
### Reproduction

https://codesandbox.io/s/spring-sound-y7j6o1?file=/src/store.ts

### Steps to reproduce the bug

1. Create a state interface with Vue app instance type.
![image](https://user-images.githubusercontent.com/11206864/222016069-a0c8ac9b-e7db-4e59-996b-4d97bb87b482.png)

2. Create a Pinia store with the state above and implement an action to set the app instance.
3. The action param should use the state interface to ensure the typing is the same.
![image](https://user-images.githubusercontent.com/11206864/222016005-f4533d18-5724-4cad-a513-172be36b1681.png)
4. Check the type error in code line 11 in [store.ts](https://codesandbox.io/s/spring-sound-y7j6o1?file=/src/store.ts)
![image](https://user-images.githubusercontent.com/11206864/222015689-b706f726-cc1a-41e8-9bc9-b94981021b98.png)

### Expected behavior

Since the action param and the state are using the exact same type, it should not complaint about the type error.

### Actual behavior

The pinia instance attach to Vue instance somehow showing different typings.

**Comment by posva** [comment] 2023-03-01 07:56
You shouldn't store the app instance in a store as it creates a cyclic reference to itself through internal properties but if you do make sure to `markRaw()` befor setting it `this.app = markRaw(data.app)`.

**Comment by posva** [comment] 2023-03-01 07:56
Duplicate of https://github.com/vuejs/core/issues/3478

**Closed as not planned by posva** 2023-03-01 07:56 UTC
