### ISSUE TITLE
Installing Pina fails with nuxt 3.0.0

### ISSUE THREAD

**Issue by tomleo** [posva/pinia#1815] opened 2022-11-20 04:17 UTC
### Reproduction

Install nuxt 3.0, then install pinia

### Steps to reproduce the bug

1. `npx nuxi init my-project`
2. `cd my-project`
3. `npm install`
4. `npm install pinia`

### Expected behavior

I expected pina to be installable with nuxt 3.0 as the project is recommended by nuxt.

### Actual behavior

❯ npm install pinia  
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.2.45
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.45" from @nuxt/vite-builder@3.0.0
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     @nuxt/vite-builder@"3.0.0" from nuxt@3.0.0
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"3.0.0" from the root project
npm ERR!   peer vue@">=2.7 || >=3" from @unhead/vue@1.0.2
npm ERR!   node_modules/@unhead/vue
npm ERR!     @unhead/vue@"^1.0.1" from @vueuse/head@1.0.16
npm ERR!     node_modules/@vueuse/head
npm ERR!       @vueuse/head@"^1.0.15" from nuxt@3.0.0
npm ERR!       node_modules/nuxt
npm ERR!         dev nuxt@"3.0.0" from the root project
npm ERR!   6 more (@vitejs/plugin-vue, @vitejs/plugin-vue-jsx, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! pinia@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.24
npm ERR!     node_modules/pinia
npm ERR!       pinia@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/tom/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2022-11-20T04_14_47_868Z-debug-0.log

### Additional information

```
- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

**Comment by posva** [comment] 2022-11-21 15:12
Duplicate of https://github.com/vuejs/pinia/issues/853

**Closed as not planned by posva** 2022-11-21 15:12 UTC
