### ISSUE TITLE
Reactive Destructure 

### ISSUE THREAD

**Issue by Bit0r** [posva/pinia#2863] opened 2024-12-23 12:11 UTC
### What problem is this solving

Can Pinia implementing [Reactive Destructure](https://vuejs.org/guide/components/props.html#reactive-props-destructure) similar to Vue 3.5?

### Proposed solution

Vue 3.5 introduces the [Reactive Props Destructure](https://vuejs.org/guide/components/props.html#reactive-props-destructure) feature, which allows direct destructuring of `props` without needing `toRefs`. Can this feature also be implemented in Pinia?

**Comment by posva** [comment] 2024-12-23 12:51
Duplicate of https://github.com/vuejs/pinia/issues/718

**Closed as not planned by posva** 2024-12-23 12:51 UTC
Labels: feature request
